[package]
name = "jinn-provider-binance"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = "2.9.7"
log = "0.4.21"
log4rs = "1.3.0"
tokio = { version = "1.10.0", features = ["full"] }
thiserror = "1.0.61"
anyhow = "1.0.86"

[dependencies.jinn-provider]
path = "../jinn-provider"
