refresh_rate: 30 seconds

# Appenders are responsible for writing log messages to a specific destination. We have two appenders: stdout and file.
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{h({l})} {t} :: {m}{n}"
  file:
    kind: rolling_file
    path: "log/provider.log"
    append: true
    encoder:
      pattern: "{d} {h({l})} {t} :: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 10 MB
      roller:
        kind: delete

# The root logger is the parent of all loggers. It is the default logger that is used when no other logger is available.
root:
  level: info
  appenders:
    - stdout

# Loggers are used to control the level of logging for a specific module. We use configuration for the provider module.
loggers:
  jinn_provider_binance:
    level: debug
    additive: true
    appenders:
      - file
